### ISSUE TITLE
'&amp;' gets converted to '&' in Rich Text Copy 

### ISSUE THREAD

**Issue by geotekberlin** [lgarron/clipboard.js#28]
This is bad because if you copy a query string like "http://example.com/index.php?oid=1&amp;pid=2" it gets converted into "http://example.com/index.php?oid=1&pid=2" which causes Libreoffice to erroneously interpret "&pid" as the greek PI character. I think you should not decode html characters when copying html but simply leave them as they are.

Besides of this bug I very much appreciate your work and would be very happy if this could be fixed

**Comment by lgarron** [comment]
Hmm, I can reproduce the issue, but I'm not sure whether there is anything to fix – this is the direct behaviour of using:

    e.clipboardData.setData("text/html", "http://example.com/index.php?oid=1&amp;pid=2");

In HTML, `&amp;` encodes `&`, so this copies the markup as it was specified.
I don't think it's appropriate to try to add extra layers of escaping for your use case – it could lead to unexpected behaviour for other use cases (ones that do rely on unescaping markup characters), and trying to cover cases across all browsers could lead to an unending game of whackamole.

As a workaround, you could either copy plain text, or find a workaround in LibreOffice ([this](https://help.libreoffice.org/Writer/Turning_Off_AutoCorrect) or [this](https://help.libreoffice.org/Common/Replace#Replacement_table))? It seems like undesirable behaviour that LibreOffice does that replacement on pasted text.

**Comment by geotekberlin** [comment]
Unfortunately there is no workaround in LibreOffice. I already filed a bug ticket over there, but I doubt that it will be fixed because rich text link copying works from all programs that I have tested so far. Only  clipboard.js fails because it cannot generate a valid http query url. By the way W3C requires that an ampersand character must be http-encoded if it is ambigous. All major browsers follow this recommendation by http-encoding the ampersand in query strings when copying a link in rich-text-mode with the effect that LibreOffice is able to correctly interpret the url.

The way it is, clipboard.js cannot be used to reliably generate URL Links that can be used in LibreOffice and possibly other programs as well. Simply passing strings in a 1:1 manner and not trying to decode anything would solve all these issues at once.

**Comment by lgarron** [comment]
What happens if you use zenorocha/clipboard.js or the API itself?

It seems to me that you're passing a string meant as "unencoded HTML" to an API that takes encoded HTML. If you write an HTML document and would like `http://example.com/index.php?oid=1&amp;pid=2` to show up on the page, you will have to [write it in the source as `http://example.com/index.php?oid=1&amp;amp;pid=2`](https://jsfiddle.net/d1y9115g/1/).

> Simply passing strings in a 1:1 manner and not trying to decode anything would solve all these issues at once.

`clipboard.js` itself does not attempt to decode anything. If you specify that a string containing `&amp;` should be interpreted as `text/html`, then I only see one correct behaviour.
In order to support what I think you're asking for, we'd have to *add* (un)decoding where there is currently none.

If you need to copy rich text containing strings with escape characters, would it be sufficient for you to crate the rich text in the DOM?
Consider this:

    var span = document.createElement("span");
    span.textContent = "http://example.com/index.php?oid=1&amp;pid=2";
    clipboard.copy(span)

**Comment by lgarron** [comment]
And since I'm no longer sure what level of escaping you want, you may want to try this instead:

    var span = document.createElement("span");
    span.textContent = "http://example.com/index.php?oid=1&pid=2";
    clipboard.copy(span);

Or just construct a link for that matter:

    var a = document.createElement("a");
    a.href = "http://example.com/index.php?oid=1&pid=2";
    a.textContent = "This is my link"
    clipboard.copy(a);
